package com.baitap03.util;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Iterator;
import java.util.Locale;
import java.util.UUID;

import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;

import jakarta.servlet.http.Part;

/** Stores decoded uploaded images outside the deployed WAR. */
public class ImageStorage {
    public static final long MAX_FILE_SIZE = 5L * 1024 * 1024;
    private static final long MAX_PIXELS = 16_000_000;
    private final Path directory;

    public ImageStorage() {
        this(Path.of(Constants.UPLOAD_DIRECTORY));
    }

    public ImageStorage(Path directory) {
        this.directory = directory.toAbsolutePath().normalize();
    }

    public String save(Part part) throws IOException {
        if (part == null || (part.getSize() == 0 && (part.getSubmittedFileName() == null || part.getSubmittedFileName().isBlank()))) {
            return null;
        }
        if (part.getSize() == 0) throw new IllegalArgumentException("Tệp ảnh đang rỗng. Vui lòng chọn ảnh khác.");
        if (part.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException("Ảnh không được vượt quá 5 MB.");
        }
        String filename = part.getSubmittedFileName();
        if (filename == null || !filename.toLowerCase(Locale.ROOT).matches(".*\\.(jpg|jpeg|png|gif)")) {
            throw new IllegalArgumentException("Chỉ chấp nhận ảnh JPG, PNG hoặc GIF.");
        }
        BufferedImage decoded;
        try (InputStream input = part.getInputStream();
             ImageInputStream stream = ImageIO.createImageInputStream(input)) {
            Iterator<ImageReader> readers = ImageIO.getImageReaders(stream);
            if (!readers.hasNext()) {
                throw new IllegalArgumentException("Tệp tải lên không phải ảnh hợp lệ.");
            }
            ImageReader reader = readers.next();
            try {
                String format = reader.getFormatName().toLowerCase(Locale.ROOT);
                if (!format.matches("jpeg|png|gif")) {
                    throw new IllegalArgumentException("Chỉ chấp nhận ảnh JPG, PNG hoặc GIF.");
                }
                reader.setInput(stream, true, true);
                if ((long) reader.getWidth(0) * reader.getHeight(0) > MAX_PIXELS) {
                    throw new IllegalArgumentException("Ảnh không được vượt quá 16 triệu điểm ảnh.");
                }
                decoded = reader.read(0);
            } finally {
                reader.dispose();
            }
        } catch (IOException e) {
            throw new IllegalArgumentException("Không đọc được ảnh. Vui lòng chọn ảnh khác.", e);
        }
        if (decoded == null) {
            throw new IllegalArgumentException("Tệp tải lên không phải ảnh hợp lệ.");
        }
        Files.createDirectories(directory);
        String storedName = "upload-" + UUID.randomUUID() + ".png";
        Path target = directory.resolve(storedName);
        try {
            // Re-encode the first frame, discarding embedded metadata and executable payloads.
            if (!ImageIO.write(decoded, "png", target.toFile())) {
                throw new IOException("Không ghi được ảnh.");
            }
            return storedName;
        } catch (IOException e) {
            Files.deleteIfExists(target);
            throw e;
        }
    }

    public void delete(String filename) throws IOException {
        // Only files generated by this component may be removed.
        if (filename != null && filename.matches("upload-[0-9a-f-]{36}\\.png")) {
            Files.deleteIfExists(directory.resolve(filename));
        }
    }
}
