USE ProductStore;
GO
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.ProductSkuSequence',N'SO') IS NULL EXEC(N'CREATE SEQUENCE dbo.ProductSkuSequence AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE');
IF COL_LENGTH('dbo.Products','sku') IS NULL EXEC(N'ALTER TABLE dbo.Products ADD sku VARCHAR(32) COLLATE Latin1_General_100_CI_AS NULL CONSTRAINT DF_Products_sku DEFAULT(''SP''+CONVERT(VARCHAR(20),NEXT VALUE FOR dbo.ProductSkuSequence))');
EXEC(N'UPDATE dbo.Products SET sku=DEFAULT WHERE sku IS NULL');
EXEC(N'ALTER TABLE dbo.Products ALTER COLUMN sku VARCHAR(32) COLLATE Latin1_General_100_CI_AS NOT NULL');
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Products') AND name='UQ_Products_sku') EXEC(N'ALTER TABLE dbo.Products ADD CONSTRAINT UQ_Products_sku UNIQUE(sku)');
IF OBJECT_ID(N'dbo.CK_Products_sku',N'C') IS NULL EXEC(N'ALTER TABLE dbo.Products ADD CONSTRAINT CK_Products_sku CHECK(LEN(sku) BETWEEN 1 AND 32 AND DATALENGTH(sku)=LEN(sku) AND sku COLLATE Latin1_General_100_BIN2 NOT LIKE ''%[^A-Z0-9_-]%'')');
COMMIT;
GO